# Generated by Django 3.0.5 on 2022-01-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageType', models.CharField(max_length=50, null=True)),
                ('PageTitle', models.CharField(max_length=200, null=True)),
                ('PageDescription', models.CharField(max_length=500, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('MobileNumber', models.CharField(max_length=15, null=True)),
                ('UpdationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAreaName', models.CharField(max_length=200, null=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LawyerName', models.CharField(max_length=200, null=True)),
                ('LawyerEmail', models.CharField(max_length=50, null=True)),
                ('LawyerMobileNo', models.CharField(max_length=15, null=True)),
                ('OfficeAddress', models.CharField(max_length=300, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('LanguageKnown', models.CharField(max_length=150, null=True)),
                ('ProfilePic', models.FileField(null=True, upload_to='')),
                ('LawyerExp', models.IntegerField(default=0)),
                ('Courts', models.CharField(max_length=150, null=True)),
                ('Website', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=500, null=True)),
                ('Status', models.CharField(max_length=50, null=True)),
                ('RegDate', models.DateTimeField(auto_now_add=True)),
                ('practiceArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer.PracticeArea')),
            ],
        ),
    ]
